[package]
name = "roc-rs"
version = "0.1.0"
authors = ["immortal infidel <immortal.infidel@gmail.com>"]
edition = "2018"
license="MIT"
description="Rate Of Change (ROC) Implementation In Rust"
repository="https://github.com/immortalinfidel/roc-rs.git"
homepage="https://github.com/immortalinfidel/roc-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ta-common = { path = "../ta-common", version = "0.1.0" }
